import "./globals.css";
import Link from "next/link";

import { Navigation } from "./Navigation";

export const metadata = {
  title: "full-stack sunny",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="me" href="https://infosec.exchange/@sunnz" />
        <link rel="me" href="https://github.com/sunnz" />
        <link rel="me" href="https://linkedin.com/in/sunyiu" />
      </head>
      <body className="font-mono text-xs">
        <Navigation />
        <main className="flex flex-col mt-10 mb-5 mx-16 lg:mx-64 xl:mx-96">
          {children}
        </main>
      </body>
    </html>
  );
}
