import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="me" href="https://infosec.exchange/@sunnz" />
        <link rel="me" href="https://github.com/sunnz" />
        <link rel="me" href="https://linkedin.com/in/sunyiu" />
      </head>
      <body className="font-mono text-xs">
        <nav>
          <ul>
            <li>
              <Link href="/">about</Link>
            </li>
            <li>
              <Link href="/links">links</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
